# Generated by Django 4.2.30 on 2026-05-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('cs_fundamentals', 'CS Fundamentals'), ('web_development', 'Web Development'), ('data_science', 'Data Science & AI'), ('programming', 'Programming Languages'), ('competitive', 'Competitive Programming'), ('blockchain', 'Blockchain & Web3'), ('ethical_hacking', 'Ethical Hacking & Security')], max_length=30),
        ),
    ]
