# Generated by Django 4.2.30 on 2026-05-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('cs_fundamentals', 'CS Fundamentals'), ('web_development', 'Web Development'), ('data_science', 'Data Science & AI'), ('programming', 'Programming Languages'), ('competitive', 'Competitive Programming'), ('blockchain', 'Blockchain & Web3'), ('ethical_hacking', 'Ethical Hacking & Security'), ('devops', 'DevOps & Cloud'), ('system_design', 'System Design'), ('mobile', 'Mobile Development'), ('gamedev', 'Game Development'), ('data_engineering', 'Data Engineering'), ('java_backend', 'Java & Spring Boot')], max_length=30),
        ),
    ]
